// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAcm_a6mkdrez0yiqhI6a2D1nR5P821Vo',
    appId: '1:441318504907:web:bf04ec17b58212e1201e4e',
    messagingSenderId: '441318504907',
    projectId: 'dietician-app-9c0b4',
    authDomain: 'dietician-app-9c0b4.firebaseapp.com',
    databaseURL: 'https://dietician-app-9c0b4-default-rtdb.firebaseio.com',
    storageBucket: 'dietician-app-9c0b4.firebasestorage.app',
    measurementId: 'G-J6ZG41J2CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3-mCZMBaXbqAPHPmR-VCz-mmemXkJQJU',
    appId: '1:441318504907:android:c1e1325ee5f4bafd201e4e',
    messagingSenderId: '441318504907',
    projectId: 'dietician-app-9c0b4',
    databaseURL: 'https://dietician-app-9c0b4-default-rtdb.firebaseio.com',
    storageBucket: 'dietician-app-9c0b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABlPOPIixkB3wOqmdOOwWTmPlAcakYnaQ',
    appId: '1:441318504907:ios:9a18bf0e8a383350201e4e',
    messagingSenderId: '441318504907',
    projectId: 'dietician-app-9c0b4',
    databaseURL: 'https://dietician-app-9c0b4-default-rtdb.firebaseio.com',
    storageBucket: 'dietician-app-9c0b4.firebasestorage.app',
    iosBundleId: 'com.example.dieticianApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABlPOPIixkB3wOqmdOOwWTmPlAcakYnaQ',
    appId: '1:441318504907:ios:9a18bf0e8a383350201e4e',
    messagingSenderId: '441318504907',
    projectId: 'dietician-app-9c0b4',
    databaseURL: 'https://dietician-app-9c0b4-default-rtdb.firebaseio.com',
    storageBucket: 'dietician-app-9c0b4.firebasestorage.app',
    iosBundleId: 'com.example.dieticianApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAcm_a6mkdrez0yiqhI6a2D1nR5P821Vo',
    appId: '1:441318504907:web:7dc7d99e088cd643201e4e',
    messagingSenderId: '441318504907',
    projectId: 'dietician-app-9c0b4',
    authDomain: 'dietician-app-9c0b4.firebaseapp.com',
    databaseURL: 'https://dietician-app-9c0b4-default-rtdb.firebaseio.com',
    storageBucket: 'dietician-app-9c0b4.firebasestorage.app',
    measurementId: 'G-QS1TRNQ0TF',
  );
}
